# Generated by Django 5.2 on 2025-05-08 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=60)),
                ('años_laborados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=10)),
                ('experiencia', models.IntegerField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(190)])),
                ('correo', models.EmailField(blank=True, max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('antecedentes_medicos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=50)),
                ('hora', models.TimeField(max_length=10)),
                ('motivo', models.TextField(blank=True, max_length=300)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.doctores')),
            ],
        ),
        migrations.AddField(
            model_name='doctores',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='api.especialidades'),
        ),
        migrations.CreateModel(
            name='especialidades_x_doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='api.doctores')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='api.especialidades')),
            ],
        ),
    ]
